services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./todo-api/
      dockerfile: Dockerfile
    container_name: goapp
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: secret
      DB_NAME: appdb
      TZ: Asia/Tokyo
    ports:
      - "8080:8080"
    volumes:
      - ./todo-api/:/todo-api/
volumes:
  db_data:

