server:
  port: "8080"

database:
  dsn: "host=postgres port=5432 user=user password=password dbname=todo_db sslmode=disable"

nats:
  url: "nats://nats:4222"
  streamName: "TODOS"
  subjects:
    - "TODOS.*"
