services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src              # ホストのソースを /src にマウント
      - ./config.yaml:/app/config.yaml:ro  # 設定ファイルだけを上書き
    depends_on:
      - postgres
      - nats
    environment:
      - DB_DSN=host=postgres port=5432 user=user password=password dbname=todo_db sslmode=disable
      - NATS_URL=nats://nats:4222

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10-alpine
    command: "-js" # JetStreamを有効化
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port

volumes:
  postgres_data:
