name: test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: build and run
        run: go run main.go
